USE food_db;

INSERT INTO foods (food_name, checkout) VALUES ('Almonds', false);
INSERT INTO foods (food_name, checkout) VALUES ('Apples', false);
INSERT INTO foods (food_name, checkout) VALUES ('Avocados', false);
INSERT INTO foods (food_name, checkout) VALUES ('Bananas', false);
INSERT INTO foods (food_name, checkout) VALUES ('Brewed Tea', false);
INSERT INTO foods (food_name, checkout) VALUES ('Broccoli', false);
INSERT INTO foods (food_name, checkout) VALUES ('Brown Rice', false);
INSERT INTO foods (food_name, checkout) VALUES ('Carrots', false);
INSERT INTO foods (food_name, checkout) VALUES ('Celery', false);
INSERT INTO foods (food_name, checkout) VALUES ('Cucumber', false);
INSERT INTO foods (food_name, checkout) VALUES ('Eggs', false);
INSERT INTO foods (food_name, checkout) VALUES ('Egg Whites', false);
INSERT INTO foods (food_name, checkout) VALUES ('Flaxseed', false);
INSERT INTO foods (food_name, checkout) VALUES ('Fresh Berries', false);
INSERT INTO foods (food_name, checkout) VALUES ('Grapefruit', false);
INSERT INTO foods (food_name, checkout) VALUES ('Grapes', false);
INSERT INTO foods (food_name, checkout) VALUES ('Peanuts', false);
INSERT INTO foods (food_name, checkout) VALUES ('Pecans', false);
INSERT INTO foods (food_name, checkout) VALUES ('Low Fat Plain Yogurt', false);
INSERT INTO foods (food_name, checkout) VALUES ('Olive Oil', false);
INSERT INTO foods (food_name, checkout) VALUES ('Pistachio Nuts', false);
INSERT INTO foods (food_name, checkout) VALUES ('Popcorn', false);
INSERT INTO foods (food_name, checkout) VALUES ('Quinoa', false);
INSERT INTO foods (food_name, checkout) VALUES ('Salmon', false);
INSERT INTO foods (food_name, checkout) VALUES ('Soybeans', false);
INSERT INTO foods (food_name, checkout) VALUES ('Spinach', false);
INSERT INTO foods (food_name, checkout) VALUES ('Sweet Potatoes', false);
INSERT INTO foods (food_name, checkout) VALUES ('Romaine Lettuce', false);
INSERT INTO foods (food_name, checkout) VALUES ('Tomatoes', false);
INSERT INTO foods (food_name, checkout) VALUES ('Walnuts', false);
INSERT INTO foods (food_name, checkout) VALUES ('Whole Grain Cereal', false);
INSERT INTO foods (food_name, checkout) VALUES ('Whole Wheat Pancakes', false);